language:
 - cpp

env:
 global:
  - GTEST_ROOT=$TRAVIS_BUILD_DIR/googletest-release-1.8.0/googletest

before_install:
 - sudo pip install gcovr

install:
 - wget https://github.com/google/googletest/archive/release-1.8.0.zip
 - unzip release-1.8.0.zip
 - mkdir $GTEST_ROOT/build
 - pushd $GTEST_ROOT/build
 - cmake -Dgtest_build_samples=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS_DEBUG='-g -fprofile-arcs -ftest-coverage' ../
 - make clean gtest
 - popd
 
script:
 - make -C $GTEST_ROOT/build |& tee build.log ; test ${PIPESTATUS[0]} -eq 0
 - $GTEST_ROOT/build/sample1_unittest --gtest_output=xml:sample1.xml
 - $GTEST_ROOT/build/sample2_unittest --gtest_output=xml:sample2.xml
 - $GTEST_ROOT/build/sample3_unittest --gtest_output=xml:sample3.xml
 - $GTEST_ROOT/build/sample4_unittest --gtest_output=xml:sample4.xml
 - $GTEST_ROOT/build/sample5_unittest --gtest_output=xml:sample5.xml
 - $GTEST_ROOT/build/sample6_unittest --gtest_output=xml:sample6.xml
 - $GTEST_ROOT/build/sample7_unittest --gtest_output=xml:sample7.xml
 - $GTEST_ROOT/build/sample8_unittest --gtest_output=xml:sample8.xml
 - $GTEST_ROOT/build/sample9_unittest --gtest_output=xml:sample9.xml
 - $GTEST_ROOT/build/sample10_unittest --gtest_output=xml:sample10.xml
 - gcovr --root ./ --filter ".*/samples/.*" --exclude ".*_unittest.*" -x -o coverage.xml

after_script:  
  - curl -s https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | sudo tar -zxvf- -C /usr/local/bin
  - testspace build.log{issues} [Tests]sample*.xml coverage.xml $TESTSPACE_TOKEN/${TRAVIS_BRANCH}#travis.Build.${TRAVIS_BUILD_NUMBER}
